export const FAKEPARK = [
  {
    id: "1",
    imageSource: "vehicules/picasso.png",
    modele: "citroen c4 grand picasso",
    description: "1.6 blue-hdi",
    price: 12690,
    year: 2016,
    energy: "diesel",
    kilometer: 99800,
    gearbox: "manuelle",
    category: "monospace",
  },
  {
    id: "2",
    imageSource: "vehicules/mercedes.png",
    modele: "mercedes-benz classe b",
    description: "160 inspiration 7G-DCT",
    price: 14990,
    year: 2017,
    energy: "diesel",
    kilometer: 95328,
    gearbox: "manuelle",
    category: "berline",
  },
  {
    id: "3",
    imageSource: "vehicules/cactus.png",
    modele: "citroen c4 cactus",
    description: "1.2 puretech shine",
    price: 9890,
    year: 2018,
    energy: "ethanol",
    kilometer: 122438,
    gearbox: "manuelle",
    category: "SUV",
  },
  {
    id: "4",
    imageSource: "vehicules/kia.png",
    modele: "kia sportage",
    description: "1.6 CRDi ISG GT Line Premium 2WD DCT7",
    price: 22890,
    year: 2020,
    energy: "diesel",
    kilometer: 97777,
    gearbox: "manuelle",
    category: "SUV",
  },
  {
    id: "5",
    imageSource: "vehicules/audi.png",
    modele: "Audi A1",
    description: "Sportback 1.0 TFSI Ultra Ambition S Tronic",
    price: 17590,
    year: 2018,
    energy: "essence",
    kilometer: 50234,
    gearbox: "manuelle",
    category: "citadine",
  },
  {
    id: "6",
    imageSource: "vehicules/peugeot.png",
    modele: "Peugeot 2008",
    description: "1.5 Blue-HDi Allure EAT8",
    price: 22500,
    year: 2021,
    energy: "diesel",
    kilometer: 18450,
    gearbox: "manuelle",
    category: "SUV",
  },
];
